morat = [
    "¿que ganas?",
    "__u__s__a__j",
    "11 besos",
    "506",
    "23",
    "a donde vamos",
    "a donde vamos a parar ",
    "acuerdate de mi",
    "al aire",
    "ahora que no puedo hablar ",
    "amor con hielo ",
    "antes de los 20",
    "aprender a quererte",
    "bajo la mesa",
    "besos en guerra",
    "causa perdida",
    "celestina",
    "como te atrves",
    "consejo de amor",
    "cuando el amor se escapa",
    "cuando nadie ve",
    "cuanto me duele",
    "cuesta abajo",
    "date la vuelta",
    "de cero",
    "devi suponerlo",
    "déjame ir",
    "del estadio al cielo", 
    "demasiado lejos",
    "di que no te vas",
    "dulse navidad",
    "el embrujo",
    "en coma",
    "en un solo dia",
    "enamorate de alguien más",
    "eres tu",
    "feo",
    "hasta por la mañana",
    "huele a gol",
    "idiota",
    "karma",
    "bella y la bestia",
    "la correcta",
    "la ultima ves - ultima ves ingles"
    "labios rotos",
    "las cometas siempre vuelan en agosto",
    "ladorna",
    "llamasa perdida",
    "lo que hará mi voca",
    "maldita costumbre",
    "mas de lo que aposte",
    "mejores amigos",
    "mi nuevo vicio",
    "mi pesadilla",
    "mi suerte",
    "mi vida entera",
    "mil tormentas",
    "no hay mas que hablar",
    "no se va",
    "no termino",
    "nuca te dije",
    "nunca volvieron",
    "nunca alrevés",
    "otras se pierden",
    "para que nadie se entere",
    "perderme"
    "parece que",
    "paris",
    "porfa no te vallas",
    "preciento",
    "primeras veses",
    "princesas",
    "punto y aparte",
    "ROCKIN' AROUND THE CHRISTMAS TREE"
    "salir con vida",
    "snata fe",
    "se que te duele",
    "sensacion de vivir",
    "segundos platos"
    "si tu te vas",
    "si la ves",
    "simplemente, pasasn",
    "sobrviviste",
    "soldado de plomo",
    "some one we use to know",
    "tabaco y chanel",
    "tarde",
    "una ves mas",
    "una y otra ves",
    "valen mas",
    "ya no estas tu",
    "yo con tigo y tu conmigo",
    "yo mas te adoro",
    "yo no meresco volver",
    ]

import random

print(random.choice(morat))
print(random.choice(morat))
print(random.choice(morat))